
device: 'cuda'

model:
  d_model: 512
  max_length: 1024
  activation: GELU
  d_hidden: 1024
  drop_prob: 0.15
  n_head: 8
  dropout: 0.1
  num_layers: 5
  patch_size: 16
  image_size: 224
  num_classes: 10

dataset:
  'train':
    name: 'MNIST'
    phase: 'train'
    image_size: 80
    loader_config: 
      batch_size: 64
  'val':
    name: 'MNIST'
    phase: 'test'
    image_size: 224
    loader_config: 
      batch_size: 64
      shuffle: true
optim:
  lr: 0.0001
train: 
  print_frequency: 100
  epochs: 10

evaluate:
  frequency: 1000
