
device: 'cpu'

model:
  model_name: 'CLASSIFI_TRANSFORMERS'
  d_model: 512
  max_length: 1024
  stride:
  activation: GELU
  d_hidden: 1024
  drop_prob: 0.15
  n_head: 8
  dropout: 0.1
  num_layers: 5
  patch_size: 16
  image_size: 224
  num_classes: 10
  pretrained: ''
dataset:
  'train':
    name: 'MNIST'
    phase: 'train'
    image_size: 80
    loader_config: 
      batch_size: 128
      shuffle: true
      # num_workers: 1
      drop_last: true
  'val':
    name: 'MNIST'
    phase: 'test'
    image_size: 80
    loader_config: 
      batch_size: 64
      shuffle: true
      drop_last: true

optim:
  lr: 0.0001
train: 
  print_frequency: 100
  epochs: 10
  save_folder: results

evaluate:
  frequency: 100
  metrics:
    - accuracy_classification
