
device: 'cuda:0'
vocab: "123456789ABCDEFGHKLMNPSTUVXYZ0R"
image_size: 400

model:
  model_name: 'VIETOCR'

  hidden_dim: 256


  transformers:
    d_model: 256
    nhead: 8
    num_encoder_layers: 6
    num_decoder_layers: 6
    dim_feedforward: 1024
    max_seq_length: 4028
    pos_dropout: 0.1
    vocab_size: 35
    trans_dropout: 0.15

  backbone: vgg19_bn
  cnn:
    pretrained: True
    # pooling stride size
    ss:
        - [3, 3]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]         
    # pooling kernel size 
    ks:
        - [3, 3]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]
    # dim of ouput feature map
    hidden: 256
    
  # pretrained: '/work/21013187/phuoc/Image_Captionning_Transformer/results/VIETOCR/10/best.pt'
  # pretrained: '/work/21013187/phuoc/Image_Captionning_Transformer/results_test_ocr/VIETOCR/70/best.pt'
  # pretrained: '/work/21013187/phuoc/Image_Captionning_Transformer/results_test_ocr/VIETOCR/93/best.pt'
  pretrained: '/work/21013187/phuoc/Image_Captionning_Transformer/results_test_ocr/VIETOCR/83/best.pt'

optim:
  lr: 0.0001

