
device: 'cpu'

model:
  model_name: VARYQWEN
  encoder:
    encoder_embed_dim: 768
    prompt_embed_dim: 256
    image_size: 640
    vit_patch_size: 16
    encoder_depth: 10
    encoder_num_heads: 12
    encoder_global_attn_indexes: [2, 5, 8, 11]
    checkpoint: null 
    verbose: True

  pretrained: '/work/21013187/phuoc/Image_Captionning_Transformer/results/VIETOCR/2/best.pt'

dataset:
  'train':
    name: 'PLATEOCR'
    phase: train
    root_dir: '/work/21013187/phuoc/Image_Captionning_Transformer/data/OCR_Phuoc/train'
    masked_language_model: True
    image_height: 224
    image_min_width: 120
    image_max_width: 448
    vocab: "123456789ABCDEFGHKLMNPSTUVXYZ0-"
    loader_config: 
      batch_size: 32
      shuffle: true
      # num_workers: 1
      drop_last: true
  'val':
    name: 'PLATEOCR'
    phase: val
    root_dir: '/work/21013187/phuoc/Image_Captionning_Transformer/data/OCR_Phuoc/val'
    masked_language_model: False
    image_height: 224
    image_min_width: 120
    image_max_width: 448
    vocab: "123456789ABCDEFGHKLMNPSTUVXYZ0-"
    loader_config: 
      batch_size: 32
      shuffle: true
      # num_workers: 1
      drop_last: true

optim:
  lr: 0.0002
train: 
  print_frequency: 10
  epochs: 100
  save_folder: results

evaluate:
  frequency: 300
  metrics:
    - accuracy_classification
